name: update-and-lint
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  update-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: composer
        run: |
          rm -r vendor 
          composer install
      - name: prettier
        run: |
          yarn global add prettier @prettier/plugin-php
          prettier . -w --end-of-line crlf --print-width 10000 --plugin /usr/local/share/.config/yarn/global/node_modules/@prettier/plugin-php/standalone.js
      - name: push
        run: |
          git add -A
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "update and lint"
          git push
